name: Playit SSH VPS

on:
  workflow_dispatch:

jobs:
  setup-ssh-vps:
    runs-on: ubuntu-22.04

    steps:
    - name: Update & Install SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh

    - name: Create VPS user
      run: |
        sudo useradd -m -s /bin/bash vpsuser
        echo "vpsuser:password123" | sudo chpasswd
        sudo usermod -aG sudo vpsuser

    - name: Download Playit
      run: |
        wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64 -O playit
        chmod +x playit

    - name: Start Playit Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        nohup ./playit --secret "$PLAYIT_AUTH_KEY" > playit.log 2>&1 &

    - name: Keep Alive
      run: sleep 21600
